  export const extMap = {
    html: 'html',
    css: 'css',
    js: 'js',
    ts: 'ts',
    json: 'json',
    md: 'md',
    txt: 'txt',
    png: 'png',
    jpg: 'jpg',
    jsx: 'jsx',
    svg: 'svg',
    mp4: 'mp4',
    py: 'py',
    java: 'java',
    vue: 'vue',
    yml: 'yml',
    yaml: 'yaml',
    env: 'env',
    lock: 'lock',
    toml: 'toml',
    scss: 'scss',
    htm: 'html',
    ttf: 'ttf'
  };
